name: 'Project Review'

on:
  workflow_call:
    inputs:
      action_ref:
        description: "Ref for workflow or action checkout"
        required: false
        default: 'main'
        type: string

jobs:
  main:
    name: 'Run'
    runs-on: ubuntu-latest
    if: ${{ github.event.review.user.login == "sjengle" }}

    steps:
      - name: 'Checkout workflows'
        id: checkout_workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'
          ref: '${{ inputs.action_ref }}'

      - name: 'Create initial issue comment'
        id: create_comment
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./workflows/.github/scripts/issue-comment.js');
            return await script({github, context, core});

      - name: 'Update pull request'
        id: update_pull
        uses: actions/github-script@v6
        env:
          COMMENT_ID: '${{ steps.create_comment.outputs.comment_id }}'
        with:
          script: |
            const script = require('./workflows/.github/scripts/review-update.js');
            return await script({github, context, core});
